### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by exedox** [Inpacchi/Manga-Tagger#12]
I have a discussion open, but figured to create this in case someone else ran into the problem.

Ok so the first go around installing everything I felt like I messed up along the way.  

My first issue was not installing in C: drive because dumb me thought that somehow things were more customizable, so I had to back track and try to reinstall everything using exact settings in github.

This was my experience in my attempt to redo it all:

Trying to install MongoDB + Compass proved to be a challenge because I had some Asus programs (Armoury Crate or something) that needed to be stopped but I couldn't so the install required a restart to work properly and I didnt do that. Then I went and clicked connect instead of fill in connections individually (see below)

![image](https://user-images.githubusercontent.com/55308770/102710478-76600100-4267-11eb-83c4-7dc7148f36a3.png)

I proceeded to install NSSM and then Manga Tagger:

I noticed on step 4 of manga installer installation:
Change the two highlighted boxes as shown below
-C:\
-Manga Tagger
This will create a directory ``C:\Manga Tagger\Manga Tagger`` because the zip file contains a Manga Tagger folder already.  I noticed that one of the steps involves running the batch file, so this is probably changed due to the updated zipped file.  I made it so then the contents of Manga Tagger folder of zip was in C:\Manga Tagger folder.

Once all was said and done I tried to use CMD admin to run ``nssm start manga_tagger`` 

The error I get: "error manga_tagger: Unexpected status SERVICE_PAUSED in response to START control."

I attempted to do all of this on a separate machine following the steps to a T but run into the same isssue starting the service.

I'm positive it's something I might have missed.  Please help.

**Comment by Inpacchi** [comment]
Normally I'd try to help you through this installation process, but I recently found a wonderful tool called PyInstaller that would allow me to generate an .exe file that might take care of a lot of the funky steps of installing yourself. I know you're anxious to use it but can I ask you to wait a couple days while I figure that out, so you can be my guinea pig for the automated installer? 😉

**Comment by Ablex222** [comment]
Has there been any progress with the installer or volume creation?

**Comment by Inpacchi** [comment]
@Ablex222 Actually, yes! You caught me at a very good time. I was in the middle of testing this over the holidays when things got hectic and forgot about it until I saw your notification yesterday. So, I got back to finishing some things up and I have an alpha build ready to go.

https://github.com/Inpacchi/Manga-Tagger/releases/tag/v1.1.0-alpha

@exedox this is for you too.

Please note that this is an **alpha** build. I've tested it in a vanilla Windows 10 environment with as minimal setup as possible, but I have not done a full deployment from scratch to know if it eliminates all issues with the original setup instructions. In the coming days I will be testing that; however I uploaded the file so that it can be tested by others as the more data about how it goes, the better.

That all being said - please let me know how it works! If an issue occurs with it - please open a new issue, just so we can keep matters organized. @exedox I will close this issue just so we can push ahead with using the executable as the primary source for using Manga Tagger.
