### ISSUE TITLE
Alpha-Build Installation Process?

### ISSUE THREAD

**Issue by Ablex222** [Inpacchi/Manga-Tagger#13]
Tested using a fresh Windows 10 VM. Installed the dependencies then ran executable. Log states that it was able to establish a database connection, however appears to crash. Could be a extension of the previous releases issue with starting the script with nssm outside of a paused state.

![image](https://user-images.githubusercontent.com/77203222/104127612-1d006480-5331-11eb-99dd-dd188df6bfb7.png)

**Comment by Inpacchi** [comment]
Fixed in 532a4b651841a4169abac25e1e1be8f096b5e928. Finally got around to resetting my Windows 10 VM and tested there; confirmed it's working now. [Here's the new alpha build release](https://github.com/Inpacchi/Manga-Tagger/releases/tag/v1.1.1-alpha). Closing this issue as it is officially resolved, but please open an issue for any other issues you find :)
