### ISSUE TITLE
Installing exe file

### ISSUE THREAD

**Issue by exedox** [Inpacchi/Manga-Tagger#16]
Is there a special way to install everything? I'm opening the exe file and it only comes up with a blank window. 

EDIT: Alright, found out you needed to open it in the Manga Tagger folder in C drive.  And that to have it start monitoring for new installs, it seems like that executable needs to be open for when the items are downloaded.

Found an issue where I suppose the manga isn't searchable if the name from the source is exact..
![image](https://user-images.githubusercontent.com/55308770/104446659-a0979c80-554f-11eb-83ba-2a96f11b6f6c.png)

I'm also getting the errors as with a manga titled exactly as it should be:

![image](https://user-images.githubusercontent.com/55308770/104447075-24ea1f80-5550-11eb-90be-faf056314033.png)

Everything should be installed since your last settings/config instructions.

**Comment by Inpacchi** [comment]
To the original issue - I've made changes to the application so that it should log to the console in the event of an error that needs to be fixed. I've also made it a bit more "portable", so a lot of changes are coming in v1.1.2-alpha. 

As to the actual issues - I'll look into them :)

**Comment by exedox** [comment]
this is still pretty great, im happy to help test! I love how you made it so then we can launch the exe prior to having fmd download stuff.  it makes it more controllable. and the way it is, at least it's detecting stuff now and doing what it's suppose to as opposed to how it was before xD

**Comment by Inpacchi** [comment]
First reported issue fixed in aad001680990e86cec6264e6170c91a21c21cbb5 - I changed the way series verification was done. Previously it was based on a comparison value between the actual downloaded manga and what MyAnimeList returned, but the threshold for the value was high. I originally programmed it this way so series weren't wrongly matched, but I figured I might have to change this at some point to account for series named such as "Peach Girl Next [EN]". So now, a comparison is done on the manga titles but also compares the authors found using MyAnimeList to AniList.

Second reported issue fixed in 286c10513ded231405971f300434722e1a34d631 - I always knew there would be more than just "chapter", "ch.", "act", etc. So I just added a case to test for "Series Title Chapter".

I should make this my tagline, lol, but here it is: as always, please open an issue if you find any other bugs, problems or questions :)

**Comment by exedox** [comment]
thanks Inpacchi, I look forward to the updated alpha build
