### ISSUE TITLE
Manga Tagger & FMD start process

### ISSUE THREAD

**Issue by Inpacchi** [Inpacchi/Manga-Tagger#21]
Manga Tagger might not be able to start FMD if it's already been started. Also, Manga Tagger should always close FMD BEFORE doing the FMD setting initialization if FMD is open. I'm not sure if Manga Tagger does this already so this should be checked.

**Comment by Ablex222** [comment]
Just a thought, but there may be problems integrating this into docker later once Linux support exists if the software relies on knowing exactly where FMD is to autoconfigure settings as needed. I am not sure if FMD could be packaged with this in docker, especially with programs like Wine being necessary. It is possible that in order to make the jump to docker, the software would have to operate completely separate to FMD and just depend on the user to make the adjustments as necessary.

**Comment by Inpacchi** [comment]
So - the issue with dockerizing Manga Tagger is that it is entirely dependent on Free Manga Downloader, and since FMD cannot be dockerized, it defeats the purpose of putting Manga Tagger into a Docker container. Granted, it can be something to explore in the future if/when I make Manga Tagger compatible with any download(er), whether automatic or manual, but that will require users to have a more control over the software and probably wouldn't make sense to dockerize anyways.

**Comment by Inpacchi** [comment]
Resolved with release [v1.1.4-alpha](https://github.com/Inpacchi/Manga-Tagger/releases/tag/v1.1.4-alpha)
